version: '3.8'
services:
  # PHP Service
  php:
    build:
      context: .
      target: php
      args:
        - APP_ENV=${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    # ports:
    #   - 8000:8000
    network_mode: host
    depends_on:
      - database

  database:
    image: postgres:16
    container_name: postgres-db
    hostname: postgres
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    network_mode: host
    # ports:
    #   - 5432:5432

  # Node Server
  node:
    build:
      context: .
      target: node
    volumes:
      - ./:/var/www
    # command: bash -c "npm install && npm run dev"
    network_mode: host
    # ports:
    #   - "5173:5173"
    tty: true

volumes:
    db-data: 
